### ISSUE TITLE
Create gen_mask CLI module

### ISSUE THREAD

**Issue by allemangD** [brain-microstructure-exploration-tools/SlicerBrainMicrostructure#3] opened 2024-04-01 20:22 UTC
Waiting for https://github.com/brain-microstructure-exploration-tools/abcd-microstructure-pipelines/pull/8

**Comment by ebrahimebrahim** [comment] 2024-04-02 13:58
duplicate of #2

**Closed as not planned by ebrahimebrahim** 2024-04-02 13:58 UTC
